services:

  poc.api:
    container_name: poc-api
    build:
      context: .
      dockerfile: POC.API/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - postgres
      - redis
      - mongo
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  postgres:
    image: postgres:16
    container_name: poc-postgres
    restart: always
    environment:
      POSTGRES_DB: POCdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: poc-redis
    restart: always
    ports:
      - "6379:6379"

  mongo:
    image: mongo:7
    container_name: poc-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  postgres-data:
  mongo-data: